
services:
  encoder-go:
    build: ./encoder-go
    volumes:
      - ./encoder-go:/go/src
    working_dir: /go/src
    command: ["tail", "-f", "/dev/null"]

  encoder-rust:
    build: ./encoder-rust
    volumes:
      - ./encoder-rust:/usr/src/app
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]
